### ISSUE TITLE
when --tp 2

### ISSUE THREAD

**Issue by maxin9966** [zhyncs/lmdeploy-build#2]
CUDA_VISIBLE_DEVICES=3,4 lmdeploy serve api_server /home/ma/work/modelscope/glm-4-9b-chat-GPTQ-Int4 --backend turbomind --model-format gptq --server-port 11231 --tp 2 --session-len 16500 --cache-max-entry-count 0.1 --model-name gpt --max-batch-size 64

Regarding the issue of memory usage when --tp 2 is enabled, why does the memory usage double when tp equals 2? Each GPU is loading a full model individually. Shouldn't the model be split and distributed across different GPU instances instead?

**Comment by zhyncs** [comment]
Good first issue! Maybe you can raise an issue at https://github.com/InternLM/lmdeploy/issues Thanks!
